### PR TITLE
Evaluate only properties requested in the query

### PR DESCRIPTION
**Pull request by dantleech**
This PR optimizes queries that select only specific columns. Before all of the properties in the node were evaluated regardless of if they were selected or not.

Using a data set of 2678 nodes:

Before: 5.29s
After: 1.24, 1.54 and 1.85s for 1, 4 and 6 columns respectively

Note that the latency seems to increase linearly, if so it would exceed the old strategy at some point, which would not be good.

### CODE REVIEW

**Comment by dbu** [comment]
there is a lot of test failures on travis, seems something breaks here.

**Comment by lsmith77** [comment]
also I would recommend to rebase on master.

**Comment by dantleech** [comment]
Tested with many properties:

````
./bin/phpcrsh -pstanton --command="SELECT i18n:ru-state, i18n:ru-changer, i18n:de-excerpt-tags, i18n:ru-template, i18n:es-navigation, i18n:ru-navigation, i18n:it-nodeType, i18n:nl-state, i18n:en-creator, i18n:de-seo-noIndex, i18n:ru-nodeType, i18n:en-template, i18n:en-changed, i18n:it-creator, i18n:ru-created, i18n:en-seo-description, i18n:en-excerpt-tags, i18n:en-seo-title, i18n:fr-creator, i18n:ru-changed, i18n:en-published, i18n:en-excerpt-images, i18n:es-created, i18n:en-excerpt-icon, i18n:nl-nodeType, i18n:de-changer, i18n:fr-template, i18n:en-url, i18n:nl-creator, i18n:it-changer, i18n:en-navigation, i18n:de-navContexts, i18n:es-creator, i18n:it-published, i18n:ru-url, i18n:es-state, i18n:es-template, i18n:en-seo-noIndex, i18n:it-created, i18n:es-changer, i18n:es-changed, i18n:en-created, i18n:fr-navigation, i18n:de-changed, i18n:it-state, i18n:nl-changer, i18n:en-navContexts, i18n:nl-created, i18n:de-excerpt-icon, i18n:fr-changed, i18n:de-seo-description, i18n:nl-changed, i18n:it-changed, i18n:de-created, i18n:de-excerpt-images, i18n:es-published, i18n:fr-created, i18n:en-seo-canonicalUrl, i18n:en-excerpt-categories, i18n:en-state, i18n:de-state, i18n:en-nodeType, i18n:nl-navigation, i18n:it-url, i18n:en-seo-keywords, i18n:it-navigation, i18n:it-template, i18n:de-seo-noFollow, i18n:fr-changer, i18n:de-nodeType, i18n:de-seo-canonicalUrl, i18n:fr-state, i18n:es-url, i18n:de-published, i18n:fr-url, sulu:order, i18n:en-seo-noFollow, i18n:de-navigation, i18n:en-changer, i18n:ru-creator, i18n:ru-published, i18n:de-seo-title, i18n:de-template, i18n:de-smartcontent, i18n:nl-template, i18n:es-nodeType, i18n:de-creator, i18n:nl-url, i18n:de-seo-keywords, i18n:de-url, i18n:nl-published, i18n:fr-nodeType, i18n:fr-published, i18n:de-excerpt-categories, i18n:it-navContexts, i18n:it-seo-title, i18n:it-seo-description, i18n:it-seo-keywords, i18n:it-seo-canonicalUrl, i18n:it-seo-noIndex, i18n:it-seo-noFollow, i18n:it-excerpt-categories, i18n:it-excerpt-tags, i18n:it-excerpt-icon, i18n:it-excerpt-images, i18n:nl-shadow-on, i18n:nl-shadow-base, i18n:nl-navContexts, i18n:nl-seo-title, i18n:nl-seo-description, i18n:nl-seo-keywords, i18n:nl-seo-canonicalUrl, i18n:nl-seo-noIndex, i18n:nl-seo-noFollow, i18n:nl-seo-hideInSitemap, i18n:nl-excerpt-categories, i18n:nl-excerpt-tags, i18n:nl-excerpt-icon, i18n:nl-excerpt-images, i18n:nl-title FROM [nt:unstructured] where jcr:mixinTypes = 'sulu:page'"
````

Took: 4.34s, so still faster than before (5.29s)

**Comment by dbu** [comment]
hm, still quite some test failures. there might be assumptions in some of the phpcr-api-tests that are not guaranteed by the spec, but some of the failures look surprising to me.

**Pull request merged**
