### PR TITLE
Revert "Fix command with --force and --drop"

### PR DESCRIPTION
**Pull request by WouterJ**
Reverts jackalope/jackalope-doctrine-dbal#275

### CODE REVIEW

**Comment by lsmith77** [comment]
huh?

**Comment by WouterJ** [comment]
Errors are already solved by the inner try...catch. The problem is that this was removed from master by you when adding `--force` (I don't know why). That now introduces problems (as dbal 2.4 throws a DBALException, which isn't catched by master)

**Comment by lsmith77** [comment]
so should this be merged?

**Comment by dbu** [comment]
@lsmith77 i guess it depends on https://github.com/jackalope/jackalope-doctrine-dbal/pull/232/files#r29992392 - wouter is asking you a question there about this bit of code

**Pull request merged**
