### PR TITLE
I tried to optimize custom node types loading

### PR DESCRIPTION
**Pull request by vondrasekpavel**
Hi,

this is my first try to load node types faster. Now I fixed number of queries but I found that we should cache fetchUserNodeTypes call.

Results on my project:

Before:
snimek obrazovky 2017-01-24 v 16 17 38

snimek obrazovky 2017-01-24 v 16 17 51

After:

snimek obrazovky 2017-01-24 v 17 22 31

snimek obrazovky 2017-01-24 v 17 22 19

ping @danrot

### CODE REVIEW

**Comment by danrot** [comment]
I have no idea what you are doing here, and where actually it is cached, but it's also working for me. Down from 73 to 13 queries :-)

**Comment by vondrasekpavel** [comment]
And is it faster in your project? :)

**Comment by danrot** [comment]
Of course, it's not like huge, but 60 queries less is a good start :) But it also feels like a single of those queries is not very slow...

**Comment by vondrasekpavel** [comment]
Yes, if @dbu will approve my PR I can continue to optimize. In this PR I only optimized number of queries nothing is cached. :)

**Comment by dbu** [comment]
thanks, great job again!

i agree its best to work in small increments, rather than a huge PR that changes several things in one go.

**Comment by vondrasekpavel** [comment]
@dbu Thank you for merge :)

**Comment by dbu** [comment]
this is really odd. the pull request was green, but now we get a build failure on master for postgres and for php 5.6. could you please check https://travis-ci.org/jackalope/jackalope-doctrine-dbal/builds/195841113 ? it seems that some of it is caused by the changes in phpcr-api-tests, i just reran an older master build that was all green, which now also fails for 5.6: https://travis-ci.org/jackalope/jackalope-doctrine-dbal/builds/193729205

**Comment by vondrasekpavel** [comment]
I think it fails because in phpcr-api-tests was updated to new PHPUnit version and old version doesn't have old methods like ::createMock

**Comment by vondrasekpavel** [comment]
I do not get it but I downloaded version from repo and launched `composer update --prefer-dist --no-interaction` and run tests with phpunit:

snimek obrazovky 2017-01-27 v 14 02 04

I try to update PHPUnit and we will see that it works on PHP 5.6 :)

**Pull request merged**
