### PR TITLE
test getting node definition with this version of jackalope

### PR DESCRIPTION
**Pull request by dbu**
this will bring in support for the recent features in jackalope and adds testing for https://github.com/jackalope/jackalope/pull/292 and https://github.com/phpcr/phpcr-api-tests/pull/163

jackrabbit: https://github.com/jackalope/jackalope-jackrabbit/pull/114

### CODE REVIEW

**Comment by dbu** [comment]
okay, so something fails for doctrine dbal. confused, for jackrabbit it does work.

**Comment by dbu** [comment]
the problem was that fixtures in jackalope-jackrabbit are not wiped after a test, but in doctrine-dbal they are. separated the test cases, now works.

**Comment by dbu** [comment]
i did this in a patch release with jackalope-jackrabbit but jackalope-doctrine-dbal master is already 1.3 so i can't easily do that here. i guess its too early to release 1.3 and backporting a new feature to 1.2 now feels wrong.

@danrot the versioning support for doctrine dbal is based on the master branch here, right? you should now be able to get the node definition from a node, hope this helps.

**Comment by danrot** [comment]
Great news! Can you rebase the versioning branch on that? I am afraid to destroy things if I rebase in my private branch.

**Comment by dbu** [comment]
yes, i think we need to rebase origin/versioning directly and not a PR on that. did it and created https://github.com/jackalope/jackalope/pull/296

**Pull request merged**
