### PR TITLE
Added integer-cast for reuqired property type

### PR DESCRIPTION
**Pull request by wachterjohannes**
Fixes issue with required property type https://github.com/jackalope/jackalope-doctrine-dbal/issues/313

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@lsmith77 @dbu what do you think?

**Comment by wachterjohannes** [comment]
tests failed but it seems that its not related to my changes: 

```
[RuntimeException]                                                           
The openssl extension is required for SSL/TLS protection but is not availab  
le. If you can not enable the openssl extension, you can disable this error  
, at your own risk, by setting the 'disable-tls' option to true.     
```

**Comment by dantleech** [comment]
+1

**Comment by dbu** [comment]
thanks. the build error seems a problem of the php 5.3.3 box on travis, all other builds are green.

**Comment by wachterjohannes** [comment]
@dbu when can we expect a release with this fix?

**Comment by dbu** [comment]
done https://github.com/jackalope/jackalope-doctrine-dbal/releases/tag/1.2.5

thanks again.

**Comment by wachterjohannes** [comment]
thanks (:

**Pull request merged**
