### PR TITLE
Test lowest versions

### PR DESCRIPTION
**Pull request by dbu**
replaces #235, now against master

### CODE REVIEW

**Comment by dbu** [comment]
there is one failure left because something is not an array. it would work with dbal 2.5.0 - shall i bump the version requirement to that? or can we avoid the error on 2.4? i guess it would be nice to not force a too high version requirement on this one to not mess with doctrine orm parallel use.

@lsmith77 do you have an idea if we can do something on our side to avoid that error? it must have worked in previous jackalope versions as we did work with dbal 2.4 at some point...

**Comment by lsmith77** [comment]
no .. I do not see how we can know if the visitors will generate any queries before hand without duplicating a lot of code.

maybe @Ocramius has an idea?

**Comment by Ocramius** [comment]
What's the problem with running latest, if I may ask?

**Comment by lsmith77** [comment]
@Ocramius

the code line that is causing the issue is:
```
foreach ($schema->toSql($connection->getDatabasePlatform()) as $sql) {
```

this results in the following stack trace:
```
1) Jackalope\Tools\Console\Command\InitDoctrineDbalCommandTest::testCommand
array_merge(): Argument #2 is not an array
/home/travis/build/jackalope/jackalope-doctrine-dbal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php:68
/home/travis/build/jackalope/jackalope-doctrine-dbal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:738
/home/travis/build/jackalope/jackalope-doctrine-dbal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:393
/home/travis/build/jackalope/jackalope-doctrine-dbal/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:335
/home/travis/build/jackalope/jackalope-doctrine-dbal/src/Jackalope/Tools/Console/Command/InitDoctrineDbalCommand.php:96
/home/travis/build/jackalope/jackalope-doctrine-dbal/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:214
/home/travis/build/jackalope/jackalope-doctrine-dbal/vendor/symfony/console/Symfony/Component/Console/Tester/CommandTester.php:66
/home/travis/build/jackalope/jackalope-doctrine-dbal/tests/Jackalope/Tools/Console/InitDoctrineDbalCommandTest.php:77
/home/travis/build/jackalope/jackalope-doctrine-dbal/tests/Jackalope/Tools/Console/InitDoctrineDbalCommandTest.php:85
```

**Comment by dbu** [comment]
@Ocramius we are trying to set up building with the lowest deps to ensure our minimal requirements are not a lie. in this case, it looks like the failing test is indeed telling that you can't run the init command with dbal 2.4

the problem is in CreateSchemaSqlCollector::acceptTable where $this->platform->getCreateTableSQL($table) is not returning the expected array. 2.5 casts that to array to avoid the problem. can we do anything to work around that for 2.4?

**Comment by Ocramius** [comment]
@dbu you need to ask @deeky666, maybe he can backport the bugfix to 2.4.x

**Comment by Ocramius** [comment]
It may be a too big BC break for a patch release tho

**Comment by dbu** [comment]
can we work around it somehow? like make sure that we give the platform something that it returns an array?

on the other hand: would there be a problem if we bump the *minimal* version requirement for dbal to 2.5? could that cause issues for users? otherwise i would say we just do that and push for upgrades.

**Comment by Ocramius** [comment]
> would there be a problem if we bump the minimal version requirement for dbal to 2.5? 

Not really: ORM 2.4 runs also with DBAL 2.5, and better than before :P

**Comment by dbu** [comment]
okay. lets go with 2.5 then

**Comment by deeky666** [comment]
The DBAL patch cannot be backported easily to 2.4 as it was fixed as  part of a new feature. We could/should however fix that issue directly in 2.4 branch.

**Comment by Ocramius** [comment]
@deeky666 we can't change the method return type :-\

**Comment by deeky666** [comment]
@Ocramius it's about [this line](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Visitor/CreateSchemaSqlCollector.php#L81) (explicit array cast) as far as I understood. That cast is missing in 2.4.

**Comment by dbu** [comment]
yep, that seems to be the issue. i am bumping to 2.5 now. but maybe 2.4 could use a backport of that fix.

**Comment by dbu** [comment]
@lsmith77 @WouterJ @dantleech good to merge? if so, we are down to one problem before releasing

**Comment by WouterJ** [comment]
Can we please look at backporting the fix to 2.4 again?

As Doctrine ORM 2.5 requires PHP 5.4, having it as dependency in your PHP 5.3 project means that all doctrine library dependencies are downgraded to Doctrine ORM 2.4. This results in an installation of jackalop-doctrine-dbal 1.2 instead of 1.3...

Or should we drop PHP 5.3 support from the CMF bundles?

**Comment by dbu** [comment]
@deeky666 what do you think about backporting the fix you mentioned to dbal 2.4 as that is the last version that supports php 5.3? imho, we should support 5.3 for another couple of months to keep working with the horribly outdated redhat enterprise servers.

**Comment by dbu** [comment]
i can do the pull request if you agree it makes sense. not sure if dbal 2.4 is still maintained at all...

**Comment by Ocramius** [comment]
2.5 still runs on 5.3: no need to backport.

**Comment by WouterJ** [comment]
@Ocramius as soon as someone is going to install Doctrine ORM in its PHP 5.3 project, every doctrine package is going to be downgraded to 2.4 as `doctrine/orm:2.5.x` requires PHP 5.4. The change that someone uses ORM and PHPCR in a project is pretty big, as not every problem can be solved with PHPCR.

**Comment by Ocramius** [comment]
I'm talking about DBAL 2.5

**Comment by deeky666** [comment]
@dbu we cannot really backport that one line as it was added as part of a feature. But sure, go ahead and do a PR against 2.4 branch that fixes the issue. I see no problems with that...

**Pull request merged**
