### PR TITLE
Loosen type hint from DBAL PDOConnection to simply PDO object

### PR DESCRIPTION
**Pull request by andylibrian**
Refer to #304

### CODE REVIEW

**Comment by lsmith77** [comment]
looks safe to me ..

@dbu wdyt?

**Comment by dbu** [comment]
if this is needed, https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L1357 is lying as \PDO is not implementing Connection. @andylibrian if you change the typehint to the \Doctrine\DBAL\Driver\Connection class instead of the PDOConnection, does it work too? that would seem the correct fix.

**Comment by dbu** [comment]
though the sqliteCreateFunction method is not in Connection or PDOConnection itself, but directly in \PDO. so lets go for \PDO. can you adjust the `@param` annotation please, and remove the now unused `use` statement?

**Comment by andylibrian** [comment]
Pushed. I squashed it as well. Please review and let me know your feedback. Thanks!

**Comment by dbu** [comment]
thanks. please ping us if you need a stable release tag for this. we just did one this morning, i would think to let things sit a bit until we see if you find other bugfixes that we should include in the release.

**Comment by andylibrian** [comment]
No problem, not in a rush. It can wait for the next stable release. Thanks again.

**Pull request merged**
