### PR TITLE
DA-47795 Correcting Oracle issues with row array key name casings.

### PR DESCRIPTION
**Pull request by jjwdesign**
Correcting Oracle issues with column name casing. Applied several array_change_key_case() function calls to lower case the data array keys. For more information see issue: https://github.com/jackalope/jackalope-doctrine-dbal/issues/173

### CODE REVIEW

**Review by dbu — COMMENTED** [review]
ah, ok. so the problem is that oracle messes up the case and then our code gets confused?

i wonder if we could decorate the connection with a wrapper instead of sprinkling the array_change_key_case all over the code. that way we could guarantee that we don't forget it somewhere, and we could use a different decorator depending on the platform so we only lowercase oracle and not the others. would be a bit tricky because we also would need a wrapper for the statement. lets try to get it working like this, and i will see if i can refactor afterwards.

i did some googling but without success, trying to find out if it would be possible to run our phpunit test suite with an oracle database. that would be helpful to know if we covered everything or if there are still problems. do you know if that is possible without buying oracle licenses or whatnot?

**Comment by dbu** [comment]
about the test failures: i will have a look in a separate branch, seems to be code rot and not related to your changes.

**Comment by dbu** [comment]
and one more thing: the master branch represents the unreleased 2.0. i would prefer if you would do the change against the 1.x branch so we can quickly release it once it is fine. there is no BC break involved so we can release it as a new minor version.

**Comment by dbu** [comment]
i fixed the static tests (phpstan and cs-fixer). the phpunit failures seem to be related to the changes in this branch. there seems to be some side effect from lowercasing everything. can you investigate that please?

**Comment by jjwdesign** [comment]
> ah, ok. so the problem is that oracle messes up the case and then our code gets confused?

Yeah, basically.

> i wonder if we could decorate the connection with a wrapper instead of sprinkling the array_change_key_case all over the code. that way we could guarantee that we don't forget it somewhere, and we could use a different decorator depending on the platform so we only lowercase oracle and not the others. would be a bit tricky because we also would need a wrapper for the statement. lets try to get it working like this, and i will see if i can refactor afterwards.

I thought I had applied a middleware on the dbal connection. I need to look back at this. Perhaps the code change was not merged or my co-worker was working with some old project code. Here's what my PHPCR nodes factory class looks like. It sets up the document manager.

```
<?php
namespace MyWhateverApp\Factory;

use Psr\Container\ContainerInterface,
    Laminas\ServiceManager\Factory\FactoryInterface,
    Doctrine\DBAL\DriverManager,
    Doctrine\DBAL\Portability\Middleware,
    Doctrine\DBAL\Configuration as ConfigurationDBAL,
    Doctrine\DBAL\Portability\Connection as ConnectionPortability,
    Doctrine\DBAL\ColumnCase,
    Jackalope\RepositoryFactoryDoctrineDBAL,
    PHPCR\SimpleCredentials,
    Doctrine\ODM\PHPCR\Configuration as ConfigurationPHPCR,
    Doctrine\Common\Annotations\AnnotationReader,
    Doctrine\ODM\PHPCR\Mapping\Driver\AnnotationDriver,
    Doctrine\ODM\PHPCR\DocumentManager;


class DoctrinePHPCRFactory implements FactoryInterface
{

    public function __invoke(ContainerInterface $container, $requestedName, array $options = null): mixed
    {

        $config = $container->get('config')['doctrine-phpcr-odm'];

        // Transport implementation
        $dbParams = [
            'driver' => $config['driver'],
            'user' => $config['dbuser'],
            'password' => $config['dbpass'],
            'dbname' => $config['dbname'],
            'host' => $config['dbhost'],
            'port' => $config['dbport'],
            'service' => $config['service'] ?? null
        ];
        $dbConfig = new ConfigurationDBAL;
        $dbConfig->setMiddlewares([
            new Middleware(ConnectionPortability::PORTABILITY_FIX_CASE, ColumnCase::LOWER)
        ]);
        // create a doctrine dbal connection
        $dbConn = DriverManager::getConnection($dbParams, $dbConfig);

        // Get jackalope repository
        $parameters = array('jackalope.doctrine_dbal_connection' => $dbConn);
        $dbal = new RepositoryFactoryDoctrineDBAL;
        $repository = $dbal->getRepository($parameters);

        $credentials = new SimpleCredentials($config['repository-username'], $config['repository-password']);
        $session = $repository->login($credentials, $config['repository-workspace']);

        // Prepare the doctrine configuration and annotations reader
        $configObj = new ConfigurationPHPCR();
        $reader = new AnnotationReader();

        // Autoloaded annotations directories
        $annotationPaths = array_unique(array_values($config['annotation-entity-path']));

        // Set Mapping Driver
        $driver = new AnnotationDriver($reader, $annotationPaths);

        $configObj->setMetadataDriverImpl($driver, false);
        $configObj->setAutoGenerateProxyClasses(true);
        $configObj->setProxyNamespace($config['proxy-namespace']);
        $configObj->setProxyDir($config['proxy-directory']);

        return DocumentManager::create($session, $configObj);
    }

}
```

**Comment by dbu** [comment]
i understood that this middleware does not fix all issues? my thought was to create a decorator class for the return value of getConnection (and the statement class) that only implements the few methods actually used in the code. that way we could prevent accidentally not lower cased things - and could apply this only when the backend is oracle.

**Comment by jjwdesign** [comment]
> i understood that this middleware does not fix all issues?

After further investigation, we had multiple document manager sessions being created. This caused some confusion with the middleware code. The middleware code shown above does in fact work. The other sessions that we had did not use the middleware to lowercase the field names. We can close this PR. Thank you.

**Comment by dbu** [comment]
oh, great to hear!

we do not instantiate the connection ourselves in RepositoryFactoryDoctrineDBAL. nonetheless, we could check if we are on oracle and add the middleware if its not already in. does #401 make sense? may i ask you to try this out with your oracle installation to see if you can then get rid of the custom logic you currently have?

**Comment by dbu** [comment]
superseeded in #401 , thanks a lot for explaining what was missing to work with oracle.

**Pull request closed without merging**
